apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1
  name: app1-srv
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: app1
  type: ClusterIP
